map:
  maker: http://geocommons.com/
  finder: http://geocommons.com/
  core: http://geocommons.com/
  embed: http://geocommons.com/javascripts/f1.api.js
  # maker: http://api-sandbox.geoiq.com/
  # finder: http://api-sandbox.geoiq.com/
  # core: http://api-sandbox.geoiq.com/
  # embed: http://api-sandbox.geoiq.com/javascripts/f1.api.js




  # actions:
  #   index:
  #     container:
  #       id: maker_map
  #       class: "span-24", "geocommons_map"
  #     script:
  #       embed: true
  #   edit:
  #     container:
  #       id:
  #       class:
  #     script:
  #       embed: true
  #       configure:

# maker:
#   new: http://maker.digitalgazette.vm/maps/new?embed=true
#   show:
#     embed: http://maker.digitalgazette.vm/javascripts/embed.js
#     maker_host: http://maker.digitalgazette.vm
#     finder_host: http://finder.digitalgazette.vm
#     core_host: http://maker.digitalgazette.vm
#   edit:
#     - http://digitalgazette.vm/maker/maps/
#     - /edit?embed=true
#   index:
#     -
